[project]
name = "ascii-art"
description = "ascii-art"
edition = "0.4.1"

[[todo]]
name = "BW color art"
priority = 4
difficulty = 1

[[todo.todo]]
name = "BW ascii art"
priority = 4
difficulty = 3

[[todo]]
name = "RGBA color art"
priority = 1
difficulty = 2

[[todo.todo]]
name = "BW ascii art"
priority = 4
difficulty = 3

[[todo]]
name = "RGB color art"
priority = 1
difficulty = 1

[[todo.todo]]
name = "RGB ascii art"
priority = 1
difficulty = 3

[[done]]
name = "RGB color art"
priority = 1
difficulty = 3
